const mongoose = require('mongoose');

const simulationStateSchema = mongoose.Schema({
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    // Future Date for this prediction
    predictionDate: { type: Date, required: true },

    // Physical Stats
    projectedWeight: { type: Number },
    projectedBodyFat: { type: Number },
    projectedMuscleMass: { type: Number },

    // Visual Data (Mocked URLs for now, possibly generated by AI later)
    frontViewUrl: { type: String },
    sideViewUrl: { type: String },

    // Simulation Parameters
    adherenceLevel: { type: Number, default: 90 }, // Assuming 90% dedication
    trainingIntensity: { type: String, enum: ['Maintenance', 'Progressive Overload', 'Athlete'], default: 'Progressive Overload' }

}, {
    timestamps: true
});

const SimulationState = mongoose.model('SimulationState', simulationStateSchema);

module.exports = SimulationState;
